services:
  - type: web
    name: andrea-tang-expense
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_SECRET_KEY
        generateValue: true
      - key: FINANCE_PASSWORD
        value: AT2022
      - key: DEMO_MODE
        value: "0"
